name: Backend Build and Push 

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest  
    # 가장 최신의 Ubuntu 러너를 사용합니다.
  
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  
      # Docker Buildx를 설정합니다.

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}  
        # GitHub Secret에서 Docker Hub 사용자 이름을 가져옵니다.
        password: ${{ secrets.DOCKERHUB_TOKEN }}     
        # GitHub Secret에서 Docker Hub 액세스 토큰을 가져옵니다.

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:  
        push: true  # 이미지를 레지스트리에 푸시합니다..
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/demo:${{ github.sha }}  

    - name: Deploy to ec2
      uses: appleboy/ssh-action@master
      id: deploy-dev
      with:
        host: ${{ secrets.HOST_DEV }} # EC2 퍼블릭 IPv4 DNS
        username: ${{ secrets.USERNAME }} # ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          sudo docker ps
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/demo:${{ github.sha }}  
          sudo docker stop demo_container
          sudo docker run -d --rm --name demo_container  -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/demo:${{ github.sha }}  
          sudo docker image prune -f
